// 📦 EDITA AQUÍ TUS PRODUCTOS
// Simplemente añade, elimina o modifica productos en este array

export const PRODUCTS = [
  {
    id: 1,
    name: 'Conjunto Jordan Fight Frizado',
    category: 'Conjuntos',
    priceRetail: 40000,
    priceWholesale: 35000,
    image: '/products/fotos/fight.png',
    images: ['/products/fotos/fight.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Conjunto premium en tela frizada. Buzo y jogging coordinados.',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  {
    id: 2,
    name: 'Remera Essentials',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/esential.png',
    images: ['/products/fotos/remeras/esential.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remera clásica con diseño Supreme',
    material: '100% Algodón Premium',
  },
  {
    id: 3,
    name: 'Conjunto Supreme Frizado',
    category: 'Conjuntos',
    priceRetail: 40000,
    priceWholesale: 35000,
    image: '/products/fotos/conjuntosupreme.png',
    images: ['/products/fotos/conjuntosupreme.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Conjunto premium en tela frizada. Buzo y jogging Diseño Supreme.',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  {
    id: 4,
    name: 'Conjunto Amiri Frizado',
    category: 'Conjuntos',
    priceRetail: 40000,
    priceWholesale: 35000,
    image: '/products/fotos/amiri.jpeg',
    images: ['/products/fotos/amiri.jpeg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Conjunto Frizado Premium diseño de Amiri.',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  {
    id: 5,
    name: 'Conjunto BOSS Frizado',
    category: 'Conjuntos',
    priceRetail: 40000,
    priceWholesale: 35000,
    image: '/products/fotos/conjuntoboss.jpeg',
    images: ['/products/fotos/conjuntoboss.jpeg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Conjunto premium en tela frizada. Buzo y jogging Diseño BOSS.',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  {
    id: 6,
    name: 'Buzo Jordan Frizado',
    category: 'Buzos',
    priceRetail: 25000,
    priceWholesale: 22000,
    image: '/products/fotos/jordancursiva.png',
    images: ['/products/fotos/jordancursiva.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Buzos premium en tela frizada Diseño Jordan',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  {
    id: 7,
    name: 'Jogging Jordan Frizado',
    category: 'Joggings',
    priceRetail: 25000,
    priceWholesale: 22000,
    image: '/products/fotos/jogging/joggingjordan.png',
    images: ['/products/fotos/jogging/joggingjordan.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Conjunto premium en tela frizada Diseño Jordan',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  {
    id: 17,
    name: 'Remera Supreme',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/supreme.png',
    images: ['/products/fotos/remeras/supreme.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remera clásica con diseño Supreme',
    material: '100% Algodón Premium',
  },
  {
    id: 8,
    name: 'Jogging Amiri Frizado',
    category: 'Joggings',
    priceRetail: 25000,
    priceWholesale: 22000,
    image: '/products/fotos/jogging/joggingamiri.png',
    images: ['/products/fotos/jogging/joggingamiri.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Jogging premium en tela frizada Diseño Amiri',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  {
    id: 9,
    name: 'Jogging Jordan Cursiva Frizado',
    category: 'Joggings',
    priceRetail: 25000,
    priceWholesale: 22000,
    image: '/products/fotos/jogging/joggingcursiva.png',
    images: ['/products/fotos/jogging/joggingcursiva.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Jogging premium en tela frizada Diseño Jordan Cursiva',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  {
    id: 18,
    name: 'Remera BOSS.',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/boss.png',
    images: ['/products/fotos/remeras/boss.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remera clásica con diseño BOSS',
    material: '100% Algodón Premium',
  },
  {
    id: 10,
    name: 'Conjunto BOSS Rojo Frizado',
    category: 'Conjuntos',
    priceRetail: 40000,
    priceWholesale: 35000,
    image: '/products/fotos/conjuntobossrojo.png',
    images: ['/products/fotos/conjuntobossrojo.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Conjunto premium en tela frizada. Buzo y jogging Diseño BOSS.',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  {
    id: 11,
    name: 'Buzo Fight Frizado',
    category: 'Buzos',
    priceRetail: 25000,
    priceWholesale: 22000,
    image: '/products/fotos/buzos/buzofight.png',
    images: ['/products/fotos/buzos/buzofight.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Buzo premium en tela frizada Diseño Fight.',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  {
    id: 12,
    name: 'Jogging Nike Frizado',
    category: 'Joggings',
    priceRetail: 25000,
    priceWholesale: 22000,
    image: '/products/fotos/jogging/joggingnike.png',
    images: ['/products/fotos/jogging/joggingnike.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Jogging premium en tela frizada Diseño Nike.',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  {
    id: 19,
    name: 'Remera Kaws',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/kaws.png',
    images: ['/products/fotos/remeras/kaws.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remera clásica con diseño Kaws',
    material: '100% Algodón Premium',
  },
  {
    id: 13,
    name: 'Buzo Supreme Frizado',
    category: 'Buzos',
    priceRetail: 25000,
    priceWholesale: 22000,
    image: '/products/fotos/buzos/buzosupreme.png',
    images: ['/products/fotos/buzos/buzosupreme.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Buzo premium en tela frizada Diseño Supreme.',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  {
    id: 14,
    name: 'Buzo Amiri Frizado',
    category: 'Buzos',
    priceRetail: 25000,
    priceWholesale: 22000,
    image: '/products/fotos/buzos/buzoamiri.png',
    images: ['/products/fotos/buzos/buzoamiri.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Buzo premium en tela frizada Diseño Amiri',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  {
    id: 15,
    name: 'Conjunto Jordan Cursiva Frizado',
    category: 'Conjuntos',
    priceRetail: 40000,
    priceWholesale: 35000,
    image: '/products/fotos/conjuntocursiva.png',
    images: ['/products/fotos/conjuntocursiva.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Conjunto premium en tela frizada. Buzo y jogging Diseño Jordan Cursiva.',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  {
    id: 16,
    name: 'Conjunto Nike Frizado',
    category: 'Conjuntos',
    priceRetail: 40000,
    priceWholesale: 35000,
    image: '/products/fotos/conjuntonike.jpeg',
    images: ['/products/fotos/conjuntonike.jpeg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Conjunto premium en tela frizada. Buzo y jogging Diseño Nike.',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  {
    id: 20,
    name: 'Remera Jordan',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/jordanblanco.png',
    images: ['/products/fotos/remeras/jordanblanco.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remera clásica Blanca con diseño Jordan',
    material: '100% Algodón Premium',
  },
  {
    id: 21,
    name: 'Remera Jordan Chico',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/jordanchico.png',
    images: ['/products/fotos/remeras/jordanchico.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remera clásica con diseño Jordan Chico',
    material: '100% Algodón Premium',
  },
  {
    id: 22,
    name: 'Remera Nike',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/nike.png',
    images: ['/products/fotos/remeras/nike.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remera clásica con diseño Nike',
    material: '100% Algodón Premium',
  },
  {
    id: 23,
    name: 'Conjunto Jordan Chico Frizado',
    category: 'Conjuntos',
    priceRetail: 40000,
    priceWholesale: 35000,
    image: '/products/fotos/conjuntojordanchico.jpeg',
    images: ['/products/fotos/conjuntojordanchico.jpeg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Conjunto premium en tela frizada. Buzo y jogging Diseño Jordan Chico.',
    material: '100% Algodón Premium',
  },
  {
    id: 24,
    name: 'Buzo BOSS Rojo Frizado',
    category: 'Buzos',
    priceRetail: 25000,
    priceWholesale: 22000,
    image: '/products/fotos/buzos/buzoboss.png',
    images: ['/products/fotos/buzos/buzoboss.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Buzo premium en tela frizada Diseño BOSS',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  {
    id: 25,
    name: 'Buzo BOSS Frizado',
    category: 'Buzos',
    priceRetail: 25000,
    priceWholesale: 22000,
    image: '/products/fotos/buzos/buzobossb.png',
    images: ['/products/fotos/buzos/buzobossb.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Buzo premium en tela frizada Diseño BOSS',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  {
    id: 26,
    name: 'Jogging Fight Frizado',
    category: 'Joggings',
    priceRetail: 25000,
    priceWholesale: 22000,
    image: '/products/fotos/jogging/joggingfight.png',
    images: ['/products/fotos/jogging/joggingfight.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Jogging premium en tela frizada Diseño Fight.',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  {
    id: 27,
    name: 'Jogging BOSS Frizado',
    category: 'Joggings',
    priceRetail: 25000,
    priceWholesale: 22000,
    image: '/products/fotos/jogging/joggingboss.png',
    images: ['/products/fotos/jogging/joggingboss.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Jogging premium en tela frizada Diseño BOSS.',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  {
    id: 28,
    name: 'Remeras',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/remeras2.png',
    images: ['/products/fotos/remeras/remeras2.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remeras Clasicas con diseños únicos y estampados de alta calidad.',
    material: '100% Algodón Premium',
  },
  {
    id: 29,
    name: 'Remeras',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/remeras1.png',
    images: ['/products/fotos/remeras/remeras1.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remeras Clasicas con diseños únicos y estampados de alta calidad.',
    material: '100% Algodón Premium',
  },
  {
    id: 30,
    name: 'Buzo Jordan en Cursiva Frizado',
    category: 'Buzos',
    priceRetail: 25000,
    priceWholesale: 22000,
    image: '/products/fotos/buzos/jordancursiva.png',
    images: ['/products/fotos/buzos/jordancursiva.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Buzo premium en tela frizada Diseño Jordan Cursiva',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  {
    id: 31,
    name: 'Buzo Kaws Frizado',
    category: 'Buzos',
    priceRetail: 25000,
    priceWholesale: 22000,
    image: '/products/fotos/buzos/buzokaws.png',
    images: ['/products/fotos/buzos/buzokaws.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Buzo premium en tela frizada Diseño Kaws',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  {
    id: 32,
    name: 'Buzo Essential Frizado',
    category: 'Buzos',
    priceRetail: 25000,
    priceWholesale: 22000,
    image: '/products/fotos/buzos/buzoesential.png',
    images: ['/products/fotos/buzos/buzoesential.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Buzo premium en tela frizada Diseño Essential',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  {
    id: 33,
    name: 'Jogging BOSS Rojo Frizado',
    category: 'Joggings',
    priceRetail: 25000,
    priceWholesale: 22000,
    image: '/products/fotos/jogging/joggingbossr.png',
    images: ['/products/fotos/jogging/joggingbossr.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Jogging premium en tela frizada Diseño BOSS Rojo.',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  {
    id: 34,
    name: 'Jogging Jordan Blanco Frizado',
    category: 'Joggings',
    priceRetail: 25000,
    priceWholesale: 22000,
    image: '/products/fotos/jogging/joggingjordanb.png',
    images: ['/products/fotos/jogging/joggingjordanb.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Jogging premium en tela frizada Diseño Jordan Blanco.',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  {
    id: 35,
    name: 'Jogging Supreme Frizado',
    category: 'Joggings',
    priceRetail: 25000,
    priceWholesale: 22000,
    image: '/products/fotos/jogging/joggingsupreme.png',
    images: ['/products/fotos/jogging/joggingsupreme.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Jogging premium en tela frizada Diseño Supreme.',
    material: 'Tela Frizada Premium 100% Algodón',
  },





  
  
]

export const CATEGORIES = ['Todos', 'Buzos', 'Remeras', 'Conjuntos', 'Joggings']

// 📞 ACTUALIZA TU NÚMERO DE WHATSAPP AQUÍ
export const WHATSAPP_NUMBER = '541122826793'

// 📱 REDES SOCIALES
export const SOCIAL_LINKS = {
  instagram: 'https://instagram.com/loqueresdrip',
  email: '@loqueresdrip@gmail.com',
  phone: '+54 9 1234-5678',
  whatsapp: `https://wa.me/${WHATSAPP_NUMBER}`,
}

// 🏙️ INFORMACIÓN DE LA EMPRESA
export const COMPANY_INFO = {
  name: 'LO QUERES DRIP',
  tagline: 'Streetwear Premium',
  description: 'Ropa urbana premium con estilo Jordan',
  city: 'Berazategui, Argentina',
}
