// 📦 EDITA AQUÍ TUS PRODUCTOS
// Simplemente añade, elimina o modifica productos en este array

export const PRODUCTS = [

  {
    id: 68,
    name: 'Remera Corteiz Negra',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/corteizn.png',
    images: ['/products/fotos/remeras/corteizn.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remeras Clasicas con diseños únicos y estampados de alta calidad.',
    material: '100% Algodón Premium',
  },
  {
    id: 65,
    name: 'Remera Armani Libertad',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/armani.jpeg',
    images: ['/products/fotos/remeras/armani.jpeg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remeras Clasicas con diseños únicos y estampados de alta calidad.',
    material: '100% Algodón Premium',
  },
  {
    id: 67,
    name: 'Remera Tommy Hilfiger',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/tommy.jpeg',
    images: ['/products/fotos/remeras/tommy.jpeg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remeras Clasicas con diseños únicos y estampados de alta calidad.',
    material: '100% Algodón Premium',
  },
  {
    id: 66,
    name: 'Remera AX',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/armani2.jpeg',
    images: ['/products/fotos/remeras/armani2.jpeg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remeras Clasicas con diseños únicos y estampados de alta calidad.',
    material: '100% Algodón Premium',
  },


  {
    id: 64,
    name: 'Remera Bape',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/bape.jpeg',
    images: ['/products/fotos/remeras/bape.jpeg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remeras Clasicas con diseños únicos y estampados de alta calidad.',
    material: '100% Algodón Premium',
  },
  {
    id: 63,
    name: 'Remera Dior',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/dior.jpeg',
    images: ['/products/fotos/remeras/dior.jpeg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remeras Clasicas con diseños únicos y estampados de alta calidad.',
    material: '100% Algodón Premium',
  },
  {
    id: 69,
    name: 'Remera Corteiz Blanca',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/corteizb.png',
    images: ['/products/fotos/remeras/corteizb.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remeras Clasicas con diseños únicos y estampados de alta calidad.',
    material: '100% Algodón Premium',
  },
  {
    id: 62,
    name: 'Remera Hugo',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/hugo.jpeg',
    images: ['/products/fotos/remeras/hugo.jpeg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remeras Clasicas con diseños únicos y estampados de alta calidad.',
    material: '100% Algodón Premium',
  },
  {
    id: 61,
    name: 'Remera Jordan Nike',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/jordannuevo.jpeg',
    images: ['/products/fotos/remeras/jordannuevo.jpeg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remeras Clasicas con diseños únicos y estampados de alta calidad.',
    material: '100% Algodón Premium',
  },
  {
    id: 60,
    name: 'Conjunto de Verano BOSS',
    category: 'Conjuntos',
    priceRetail: 30000,
    priceWholesale: 26000,
    image: '/products/conjuntos/boss.png',
    images: ['/products/conjuntos/boss.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Conjuntos de Verano Diferentes Modelos',
    material: '100% Algodón Premium',
  },
  {
    id: 59,
    name: 'Conjunto de Verano Bape',
    category: 'Conjuntos',
    priceRetail: 30000,
    priceWholesale: 26000,
    image: '/products/conjuntos/bape.jpeg',
    images: ['/products/conjuntos/bape.jpeg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Conjuntos de Verano Diferentes Modelos',
    material: '100% Algodón Premium',
  },
  {
    id: 58,
    name: 'Conjunto de Verano Emporio Armani',
    category: 'Conjuntos',
    priceRetail: 30000,
    priceWholesale: 26000,
    image: '/products/conjuntos/armani.jpeg',
    images: ['/products/conjuntos/armani.jpeg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Conjuntos de Verano Diferentes Modelos',
    material: '100% Algodón Premium',
  },
  {
    id: 57,
    name: 'Conjunto de Verano Amiri',
    category: 'Conjuntos',
    priceRetail: 30000,
    priceWholesale: 26000,
    image: '/products/conjuntos/amiri.png',
    images: ['/products/conjuntos/amiri.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Conjuntos de Verano Diferentes Modelos',
    material: '100% Algodón Premium',
  },
  {
    id: 56,
    name: 'Conjunto de Verano Nike',
    category: 'Conjuntos',
    priceRetail: 30000,
    priceWholesale: 26000,
    image: '/products/conjuntos/nike.png',
    images: ['/products/conjuntos/nike.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Conjuntos de Verano Diferentes Modelos',
    material: '100% Algodón Premium',
  },
  {
    id: 55,
    name: 'Conjunto de Verano Calvin Klein',
    category: 'Conjuntos',
    priceRetail: 30000,
    priceWholesale: 26000,
    image: '/products/conjuntos/calvinklein.png',
    images: ['/products/conjuntos/calvinklein.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Conjuntos de Verano Diferentes Modelos',
    material: '100% Algodón Premium',
  },

  {
    id: 53,
    name: 'Conjunto de Verano Jordan Rojo',
    category: 'Conjuntos',
    priceRetail: 30000,
    priceWholesale: 26000,
    image: '/products/conjuntos/jordanr.png',
    images: ['/products/conjuntos/jordanr.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Conjuntos de Verano Diferentes Modelos',
    material: '100% Algodón Premium',
  },

  {
    id: 50,
    name: 'Conjunto de Verano Dior',
    category: 'Conjuntos',
    priceRetail: 30000,
    priceWholesale: 26000,
    image: '/products/conjuntos/ChatgptDior.png',
    images: ['/products/conjuntos/ChatgptDior.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Conjuntos de Verano Diferentes Modelos',
    material: '100% Algodón Premium',
  },
  {
    id: 54,
    name: 'Conjunto de Verano Supreme',
    category: 'Conjuntos',
    priceRetail: 30000,
    priceWholesale: 26000,
    image: '/products/conjuntos/supreme.png',
    images: ['/products/conjuntos/supreme.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Conjuntos de Verano Diferentes Modelos',
    material: '100% Algodón Premium',
  },

  {
    id: 51,
    name: 'Conjunto de Verano Tommy Hilfiger',
    category: 'Conjuntos',
    priceRetail: 30000,
    priceWholesale: 26000,
    image: '/products/conjuntos/tommy.jpeg',
    images: ['/products/conjuntos/tommy.jpeg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Conjuntos de Verano Diferentes Modelos',
    material: '100% Algodón Premium',
  },

  {
    id: 52,
    name: 'Conjunto de Verano Corteiz',
    category: 'Conjuntos',
    priceRetail: 30000,
    priceWholesale: 26000,
    image: '/products/conjuntos/corteiz.png',
    images: ['/products/conjuntos/corteiz.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Conjuntos de Verano Diferentes Modelos',
    material: '100% Algodón Premium',
  },

  {
    id: 41,
    name: 'Remera Balenciaga',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/balenciaga.jpeg',
    images: ['/products/fotos/remeras/balenciaga.jpeg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remeras Clasicas con diseños únicos y estampados de alta calidad.',
    material: '100% Algodón Premium',
  },

  
  {
    id: 2,
    name: 'Remera Essentials',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/esential.png',
    images: ['/products/fotos/remeras/esential.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remera clásica con diseño Supreme',
    material: '100% Algodón Premium',
  },
  
  
  
  {
    id: 6,
    name: 'Buzo Jordan Frizado',
    category: 'Buzos',
    priceRetail: 25000,
    priceWholesale: 20000,
    image: '/products/fotos/buzos/jordancursiva.png',
    images: ['/products/fotos/buzos/jordancursiva.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Buzos premium en tela frizada Diseño Jordan',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  
  {
    id: 17,
    name: 'Remera Supreme',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/supreme.png',
    images: ['/products/fotos/remeras/supreme.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remera clásica con diseño Supreme',
    material: '100% Algodón Premium',
  },
  
  
  {
    id: 18,
    name: 'Remera BOSS.',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/boss.png',
    images: ['/products/fotos/remeras/boss.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remera clásica con diseño BOSS',
    material: '100% Algodón Premium',
  },
  
  {
    id: 11,
    name: 'Buzo Fight Frizado',
    category: 'Buzos',
    priceRetail: 25000,
    priceWholesale: 20000,
    image: '/products/fotos/buzos/buzofight.png',
    images: ['/products/fotos/buzos/buzofight.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Buzo premium en tela frizada Diseño Fight.',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  
  {
    id: 19,
    name: 'Remera Kaws',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/kaws.png',
    images: ['/products/fotos/remeras/kaws.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remera clásica con diseño Kaws',
    material: '100% Algodón Premium',
  },
  {
    id: 13,
    name: 'Buzo Supreme Frizado',
    category: 'Buzos',
    priceRetail: 25000,
    priceWholesale: 20000,
    image: '/products/fotos/buzos/buzosupreme.png',
    images: ['/products/fotos/buzos/buzosupreme.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Buzo premium en tela frizada Diseño Supreme.',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  {
    id: 14,
    name: 'Buzo Amiri Frizado',
    category: 'Buzos',
    priceRetail: 25000,
    priceWholesale: 20000,
    image: '/products/fotos/buzos/buzoamiri.png',
    images: ['/products/fotos/buzos/buzoamiri.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Buzo premium en tela frizada Diseño Amiri',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  
  
  {
    id: 20,
    name: 'Remera Jordan',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/jordanblanco.png',
    images: ['/products/fotos/remeras/jordanblanco.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remera clásica Blanca con diseño Jordan',
    material: '100% Algodón Premium',
  },
  {
    id: 21,
    name: 'Remera Jordan Chico',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/jordanchico.png',
    images: ['/products/fotos/remeras/jordanchico.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remera clásica con diseño Jordan Chico',
    material: '100% Algodón Premium',
  },
  {
    id: 22,
    name: 'Remera Nike',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/nike.png',
    images: ['/products/fotos/remeras/nike.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remera clásica con diseño Nike',
    material: '100% Algodón Premium',
  },
  
  {
    id: 24,
    name: 'Buzo BOSS Rojo Frizado',
    category: 'Buzos',
    priceRetail: 25000,
    priceWholesale: 20000,
    image: '/products/fotos/buzos/buzoboss.png',
    images: ['/products/fotos/buzos/buzoboss.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Buzo premium en tela frizada Diseño BOSS',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  {
    id: 25,
    name: 'Buzo BOSS Frizado',
    category: 'Buzos',
    priceRetail: 25000,
    priceWholesale: 20000,
    image: '/products/fotos/buzos/buzobossb.png',
    images: ['/products/fotos/buzos/buzobossb.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Buzo premium en tela frizada Diseño BOSS',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  
  
  {
    id: 28,
    name: 'Remeras',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/remeras2.png',
    images: ['/products/fotos/remeras/remeras2.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remeras Clasicas con diseños únicos y estampados de alta calidad.',
    material: '100% Algodón Premium',
  },
  {
    id: 29,
    name: 'Remeras',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/remeras1.png',
    images: ['/products/fotos/remeras/remeras1.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remeras Clasicas con diseños únicos y estampados de alta calidad.',
    material: '100% Algodón Premium',
  },
  {
    id: 30,
    name: 'Buzo Jordan en Cursiva Frizado',
    category: 'Buzos',
    priceRetail: 25000,
    priceWholesale: 22000,
    image: '/products/fotos/buzos/jordancursiva.png',
    images: ['/products/fotos/buzos/jordancursiva.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Buzo premium en tela frizada Diseño Jordan Cursiva',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  {
    id: 31,
    name: 'Buzo Kaws Frizado',
    category: 'Buzos',
    priceRetail: 25000,
    priceWholesale: 20000,
    image: '/products/fotos/buzos/buzokaws.png',
    images: ['/products/fotos/buzos/buzokaws.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Buzo premium en tela frizada Diseño Kaws',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  {
    id: 32,
    name: 'Buzo Essential Frizado',
    category: 'Buzos',
    priceRetail: 25000,
    priceWholesale: 20000,
    image: '/products/fotos/buzos/buzoesential.png',
    images: ['/products/fotos/buzos/buzoesential.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Buzo premium en tela frizada Diseño Essential',
    material: 'Tela Frizada Premium 100% Algodón',
  },
  
  {
    id: 37,
    name: 'Remera Nike Dorado',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/nikeremera.jpeg',
    images: ['/products/fotos/remeras/nikeremera.jpeg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remeras Clasicas con diseños únicos y estampados de alta calidad.',
    material: '100% Algodón Premium',
  },
  {
    id: 38,
    name: 'Remera Amiri',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/amiriremera.jpeg',
    images: ['/products/fotos/remeras/amiriremera.jpeg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remeras Clasicas con diseños únicos y estampados de alta calidad.',
    material: '100% Algodón Premium',
  },
  {
    id: 39,
    name: 'Remera Balenciaga',
    category: 'Remeras',
    priceRetail: 12000,
    priceWholesale: 10000,
    image: '/products/fotos/remeras/balenciaga.jpeg',
    images: ['/products/fotos/remeras/balenciaga.jpeg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Remeras Clasicas con diseños únicos y estampados de alta calidad.',
    material: '100% Algodón Premium',
  },





  
  
]

export const CATEGORIES = ['Todos', 'Buzos', 'Remeras', 'Conjuntos', 'Shorts']

// 📞 ACTUALIZA TU NÚMERO DE WHATSAPP AQUÍ
export const WHATSAPP_NUMBER = '541178174007' // Formato: Código de país + número (sin espacios ni guiones)

// 📱 REDES SOCIALES
export const SOCIAL_LINKS = {
  instagram: 'https://instagram.com/loqueresdrip',
  email: '@loqueresdrip@gmail.com',
  phone: '+54 9 1178174007',
  whatsapp: `https://wa.me/${WHATSAPP_NUMBER}`,
}

// 🏙️ INFORMACIÓN DE LA EMPRESA
export const COMPANY_INFO = {
  name: 'LO QUERES DRIP',
  tagline: 'Streetwear Premium',
  description: 'Ropa urbana premium con estilo Jordan',
  city: 'Berazategui, Argentina',
}
